name: weboptify
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Day 10 Packages
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true

  assets:
    - assets/5d12a8c0-a918-4c78-b75b-aa8fb03d6dcf.png

flutter_launcher_icons:
  android: true
  image_path: "assets/5d12a8c0-a918-4c78-b75b-aa8fb03d6dcf.png"